version: 1
disable_existing_loggers: False


formatters:
  verbose:
    format: '[%(asctime)s] [%(levelname)s] %(name)s: %(message)s'
#  verbose:
#    format: '%(message)s'
#  verbose:
#    format: '%(args)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: verbose

  file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/django_log.log
    maxBytes: 1048576
    backupCount: 5

loggers:
  # настройка родительского регистратора django
  django:
    level: INFO
    handlers:
      - console
      - file
    propagate: True
