# Generated by Django 5.0.6 on 2024-07-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Данные сайта', 'verbose_name_plural': 'Данные сайта'},
        ),
        migrations.AddField(
            model_name='data',
            name='tel',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
