# Generated by Django 5.0.6 on 2024-07-08 10:58

import home_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_alter_data_options_data_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplesOfWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home_page.models.example_work_upload)),
                ('alt', models.CharField(default='example_work', editable=False, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
