# Generated by Django 5.0.6 on 2024-07-08 13:58

import django.db.models.deletion
import home_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_examplesofworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.AlterModelOptions(
            name='examplesofworks',
            options={'verbose_name': 'Примеры работ', 'verbose_name_plural': 'Примеры работ'},
        ),
        migrations.CreateModel(
            name='MainImgProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home_page.models.main_img_product_upload)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='home_page.product')),
            ],
        ),
        migrations.CreateModel(
            name='ImgProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home_page.models.img_product_upload)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home_page.product')),
            ],
        ),
    ]
