# Generated by Django 5.0.6 on 2024-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_product_alter_examplesofworks_options_mainimgproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplesofworks',
            options={'verbose_name': 'Пример работы', 'verbose_name_plural': 'Примеры работ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
