# Generated by Django 5.0.6 on 2024-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_alter_examplesofworks_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgproduct',
            name='alt',
            field=models.CharField(default='img', max_length=50),
        ),
        migrations.AddField(
            model_name='mainimgproduct',
            name='alt',
            field=models.CharField(default='img', max_length=50),
        ),
    ]
