# Generated by Django 5.0.6 on 2024-07-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_imgproduct_alt_mainimgproduct_alt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgproduct',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='mainimgproduct',
            options={'verbose_name': 'Главное изображение'},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
