# Generated by Django 5.0.6 on 2024-07-10 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_alter_imgproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Длина имени не может быть меньше двух знаков')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Недопустимое значение для email')])),
                ('tel', models.TextField(validators=[django.core.validators.RegexValidator(message='Недопустимое значение для телефона', regex='+7\\d{10}')])),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Сообщение слишком короткое')])),
            ],
        ),
    ]
