# Generated by Django 5.0.6 on 2024-07-11 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='tel',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Недопустимое значение для телефона', regex='/+7\\d{10}/')]),
        ),
    ]
