# Generated by Django 5.0.6 on 2024-07-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
