# Generated by Django 5.0.6 on 2024-07-12 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tel',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Недопустимое значение для телефона', regex='/+7\\d*/')]),
        ),
    ]
