# Generated by Django 5.0.6 on 2024-07-12 11:33

import home_page.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0012_alter_message_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tel',
            field=models.TextField(validators=[home_page.validators.tel_ru_validator]),
        ),
    ]
