# Generated by Django 5.0.6 on 2024-07-12 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0014_alter_message_email_alter_message_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Недопустимое значение для email')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Сообщение меньше 10 знаков')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Длина имени не может быть меньше двух знаков')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='tel',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Недопустимое значение для телефона, формат +7 999 999 99 99', regex='\\+7\\d{10}')]),
        ),
    ]
