# Generated by Django 5.0.6 on 2024-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0016_alter_message_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
