# Generated by Django 5.0.6 on 2024-07-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0018_alter_imgproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home_page.product'),
        ),
    ]
